apiVersion: apps/v1
kind: Deployment
metadata:
  name: ippr
  namespace: ippr
spec:
  selector:
    matchLabels:
      app: ippr
  template:
    metadata:
      labels:
        app: ippr
    spec:
      serviceAccountName: ippr
      restartPolicy: Always
      containers:
      - name: ippr
        image: us-docker.pkg.dev/kubecon-demos-project/kubecon/ippr:v0.1.0
        ports:
        - containerPort: 8080
        resizePolicy:
        - resourceName: cpu
          restartPolicy: NotRequired
        - resourceName: memory
          restartPolicy: RestartContainer
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 2
